=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'date'
require 'time'

module OpenapiClient
  # EnvMetricV3 describes a envMetricV3
  class EnvMetricV3ResponseBody
    # created time
    attr_accessor :created_at

    # CveID of envMetricV3
    attr_accessor :cve_id

    # MA of envMetricV3
    attr_accessor :ma

    # MAC of envMetricV3
    attr_accessor :mac

    # MAV of envMetricV3
    attr_accessor :mav

    # MC of envMetricV3
    attr_accessor :mc

    # MPR of envMetricV3
    attr_accessor :mpr

    # MS of envMetricV3
    attr_accessor :ms

    # MUI of envMetricV3
    attr_accessor :mui

    # ServerRoleID of envMetricV3
    attr_accessor :role_id

    # ServerRoleName of envMetricV3
    attr_accessor :role_name

    # updated time
    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'created_at' => :'createdAt',
        :'cve_id' => :'cveID',
        :'ma' => :'ma',
        :'mac' => :'mac',
        :'mav' => :'mav',
        :'mc' => :'mc',
        :'mpr' => :'mpr',
        :'ms' => :'ms',
        :'mui' => :'mui',
        :'role_id' => :'roleID',
        :'role_name' => :'roleName',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'created_at' => :'Time',
        :'cve_id' => :'String',
        :'ma' => :'String',
        :'mac' => :'String',
        :'mav' => :'String',
        :'mc' => :'String',
        :'mpr' => :'String',
        :'ms' => :'String',
        :'mui' => :'String',
        :'role_id' => :'Integer',
        :'role_name' => :'String',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::EnvMetricV3ResponseBody` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::EnvMetricV3ResponseBody`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'cve_id')
        self.cve_id = attributes[:'cve_id']
      end

      if attributes.key?(:'ma')
        self.ma = attributes[:'ma']
      end

      if attributes.key?(:'mac')
        self.mac = attributes[:'mac']
      end

      if attributes.key?(:'mav')
        self.mav = attributes[:'mav']
      end

      if attributes.key?(:'mc')
        self.mc = attributes[:'mc']
      end

      if attributes.key?(:'mpr')
        self.mpr = attributes[:'mpr']
      end

      if attributes.key?(:'ms')
        self.ms = attributes[:'ms']
      end

      if attributes.key?(:'mui')
        self.mui = attributes[:'mui']
      end

      if attributes.key?(:'role_id')
        self.role_id = attributes[:'role_id']
      end

      if attributes.key?(:'role_name')
        self.role_name = attributes[:'role_name']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @cve_id.nil?
        invalid_properties.push('invalid value for "cve_id", cve_id cannot be nil.')
      end

      if @ma.nil?
        invalid_properties.push('invalid value for "ma", ma cannot be nil.')
      end

      if @mac.nil?
        invalid_properties.push('invalid value for "mac", mac cannot be nil.')
      end

      if @mav.nil?
        invalid_properties.push('invalid value for "mav", mav cannot be nil.')
      end

      if @mc.nil?
        invalid_properties.push('invalid value for "mc", mc cannot be nil.')
      end

      if @mpr.nil?
        invalid_properties.push('invalid value for "mpr", mpr cannot be nil.')
      end

      if @ms.nil?
        invalid_properties.push('invalid value for "ms", ms cannot be nil.')
      end

      if @mui.nil?
        invalid_properties.push('invalid value for "mui", mui cannot be nil.')
      end

      if @role_id.nil?
        invalid_properties.push('invalid value for "role_id", role_id cannot be nil.')
      end

      if @role_name.nil?
        invalid_properties.push('invalid value for "role_name", role_name cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @created_at.nil?
      return false if @cve_id.nil?
      return false if @ma.nil?
      return false if @mac.nil?
      return false if @mav.nil?
      return false if @mc.nil?
      return false if @mpr.nil?
      return false if @ms.nil?
      return false if @mui.nil?
      return false if @role_id.nil?
      return false if @role_name.nil?
      return false if @updated_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          created_at == o.created_at &&
          cve_id == o.cve_id &&
          ma == o.ma &&
          mac == o.mac &&
          mav == o.mav &&
          mc == o.mc &&
          mpr == o.mpr &&
          ms == o.ms &&
          mui == o.mui &&
          role_id == o.role_id &&
          role_name == o.role_name &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [created_at, cve_id, ma, mac, mav, mc, mpr, ms, mui, role_id, role_name, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
