=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CveApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CveApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CveApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CveApi' do
    it 'should create an instance of CveApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CveApi)
    end
  end

  # unit tests for cve_get_cve_detail
  # getCveDetail cve
  # cve detail
  # @param cve_id Cve ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization api key auth
  # @return [CveGetCveDetailResponseBody]
  describe 'cve_get_cve_detail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cve_get_cve_list
  # getCveList cve
  # cve list
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page Number
  # @option opts [Integer] :limit Limit
  # @option opts [Integer] :offset Offset
  # @option opts [Integer] :filter_server_id ServerID filter
  # @option opts [Integer] :filter_role_id ServerRoleID filter
  # @option opts [Integer] :filter_pkg_id PackageID filter
  # @option opts [Integer] :filter_cpe_id CpeID filter
  # @option opts [String] :authorization api key auth
  # @return [CveGetCveListResponseBody]
  describe 'cve_get_cve_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
