=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LockfileApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LockfileApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LockfileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LockfileApi' do
    it 'should create an instance of LockfileApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LockfileApi)
    end
  end

  # unit tests for lockfile_add_lockfile
  # addLockfile lockfile
  # add lockfile
  # @param add_lockfile_request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization api key auth
  # @return [LockfileAddLockfileResponseBody]
  describe 'lockfile_add_lockfile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lockfile_delete_lockfile
  # deleteLockfile lockfile
  # lockfile delete
  # @param lockfile_id Lockfile ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization api key auth
  # @return [nil]
  describe 'lockfile_delete_lockfile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lockfile_get_lockfile_detail
  # getLockfileDetail lockfile
  # lockfile detail
  # @param lockfile_id Lockfile ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization api key auth
  # @return [LockfileGetLockfileDetailResponseBody]
  describe 'lockfile_get_lockfile_detail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lockfile_get_lockfile_list
  # getLockfileList lockfile
  # lockfile list
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page Number
  # @option opts [Integer] :limit Limit
  # @option opts [Integer] :offset Offset
  # @option opts [Integer] :filter_server_id ServerID filter
  # @option opts [String] :filter_path Path filter
  # @option opts [String] :authorization api key auth
  # @return [LockfileGetLockfileListResponseBody]
  describe 'lockfile_get_lockfile_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lockfile_update_lockfile
  # updateLockfile lockfile
  # update lockfile
  # @param lockfile_id Lockfile ID
  # @param update_lockfile_request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization api key auth
  # @return [LockfileUpdateLockfileResponseBody]
  describe 'lockfile_update_lockfile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
