=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PkgCpeDeleteCpeDeprecatedRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PkgCpeDeleteCpeDeprecatedRequestBody do
  let(:instance) { OpenapiClient::PkgCpeDeleteCpeDeprecatedRequestBody.new }

  describe 'test an instance of PkgCpeDeleteCpeDeprecatedRequestBody' do
    it 'should create an instance of PkgCpeDeleteCpeDeprecatedRequestBody' do
      expect(instance).to be_instance_of(OpenapiClient::PkgCpeDeleteCpeDeprecatedRequestBody)
    end
  end
  describe 'test attribute "cpe_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
