=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PkgCpeGetPkgCpeListResponseBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PkgCpeGetPkgCpeListResponseBody do
  let(:instance) { OpenapiClient::PkgCpeGetPkgCpeListResponseBody.new }

  describe 'test an instance of PkgCpeGetPkgCpeListResponseBody' do
    it 'should create an instance of PkgCpeGetPkgCpeListResponseBody' do
      expect(instance).to be_instance_of(OpenapiClient::PkgCpeGetPkgCpeListResponseBody)
    end
  end
  describe 'test attribute "paging"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "pkg_cpes"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
