=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PkgCpeAddCpeRequestBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PkgCpeAddCpeRequestBody do
  let(:instance) { OpenapiClient::PkgCpeAddCpeRequestBody.new }

  describe 'test an instance of PkgCpeAddCpeRequestBody' do
    it 'should create an instance of PkgCpeAddCpeRequestBody' do
      expect(instance).to be_instance_of(OpenapiClient::PkgCpeAddCpeRequestBody)
    end
  end
  describe 'test attribute "cpe_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "is_uri"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "server_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
