=begin
#Future Vuls Public API

#Future Vuls Public API

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/advisory_response_body'
require 'openapi_client/models/affected_proc_response_body'
require 'openapi_client/models/child_task_response_body'
require 'openapi_client/models/cve_get_cve_detail_response_body'
require 'openapi_client/models/cve_get_cve_list_response_body'
require 'openapi_client/models/cve_list_response_body'
require 'openapi_client/models/cwe_response_body'
require 'openapi_client/models/detection_method_response_body'
require 'openapi_client/models/detection_tool_response_body'
require 'openapi_client/models/env_metric_v2_response_body'
require 'openapi_client/models/env_metric_v3_response_body'
require 'openapi_client/models/library_pkg_child_response_body'
require 'openapi_client/models/lockfile_add_lockfile_request_body'
require 'openapi_client/models/lockfile_add_lockfile_response_body'
require 'openapi_client/models/lockfile_get_lockfile_detail_response_body'
require 'openapi_client/models/lockfile_get_lockfile_list_response_body'
require 'openapi_client/models/lockfile_list_response_body'
require 'openapi_client/models/lockfile_update_lockfile_request_body'
require 'openapi_client/models/lockfile_update_lockfile_response_body'
require 'openapi_client/models/need_restart_proc_response_body'
require 'openapi_client/models/paging_response_body'
require 'openapi_client/models/pkg_cpe_add_cpe_request_body'
require 'openapi_client/models/pkg_cpe_add_cpe_response_body'
require 'openapi_client/models/pkg_cpe_child_response_body'
require 'openapi_client/models/pkg_cpe_delete_cpe_deprecated_request_body'
require 'openapi_client/models/pkg_cpe_get_cpe_detail_response_body'
require 'openapi_client/models/pkg_cpe_get_pkg_cpe_list_response_body'
require 'openapi_client/models/pkg_cpe_get_pkg_detail_response_body'
require 'openapi_client/models/pkg_cpe_list_response_body'
require 'openapi_client/models/role_get_role_detail_response_body'
require 'openapi_client/models/role_get_role_list_response_body'
require 'openapi_client/models/role_list_response_body'
require 'openapi_client/models/role_update_role_request_body'
require 'openapi_client/models/role_update_role_response_body'
require 'openapi_client/models/sec_metric_response_body'
require 'openapi_client/models/server_child_response_body'
require 'openapi_client/models/server_create_pkg_paste_server_request_body'
require 'openapi_client/models/server_create_pkg_paste_server_response_body'
require 'openapi_client/models/server_get_server_detail_by_uuid_response_body'
require 'openapi_client/models/server_get_server_detail_response_body'
require 'openapi_client/models/server_get_server_list_response_body'
require 'openapi_client/models/server_list_response_body'
require 'openapi_client/models/server_tag_response_body'
require 'openapi_client/models/server_update_pkg_paste_server_request_body'
require 'openapi_client/models/server_update_server_request_body'
require 'openapi_client/models/server_update_server_response_body'
require 'openapi_client/models/task_add_task_comment_request_body'
require 'openapi_client/models/task_add_task_comment_response_body'
require 'openapi_client/models/task_comment_response_body'
require 'openapi_client/models/task_get_task_detail_response_body'
require 'openapi_client/models/task_get_task_list_response_body'
require 'openapi_client/models/task_list_response_body'
require 'openapi_client/models/task_update_task_ignore_request_body'
require 'openapi_client/models/task_update_task_ignore_response_body'
require 'openapi_client/models/task_update_task_request_body'
require 'openapi_client/models/task_update_task_response_body'
require 'openapi_client/models/tmp_metric_response_body'

# APIs
require 'openapi_client/api/cve_api'
require 'openapi_client/api/health_api'
require 'openapi_client/api/lockfile_api'
require 'openapi_client/api/pkg_cpe_api'
require 'openapi_client/api/role_api'
require 'openapi_client/api/server_api'
require 'openapi_client/api/task_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
